---
Version: "2012-10-17"
Statement:
  - Sid: "RevokeSecurityGroup"
    Action:
      - "ec2:RevokeSecurityGroupIngress"
      - "ec2:RevokeSecurityGroupEgress"
      - "ec2:DescribeSecurityGroups"
    Effect: "Allow"
    Resource: "*"
